import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ANIMATION_GROUP_COUNT,
  type SpineAnimationGroup,
  type SpineAssetsConfig,
  type SpineSkeletonConfig,
} from "./types";
import { listFilesRecursive, toAssetPath } from "./shared/utils";

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS_DIR = path.join(ROOT_DIR, "public", "assets");
const OUTPUT_PATH = path.join(
  ROOT_DIR,
  "src",
  "generated",
  "spineAssetsConfig.ts",
);

interface SpineJsonDocument {
  skeleton?: unknown;
  animations?: Record<string, unknown>;
}

function collectByExtension(files: string[], extension: string): Set<string> {
  return new Set(
    files.filter((filePath) => filePath.toLowerCase().endsWith(extension)),
  );
}

function resolveAtlasPath(
  jsonPath: string,
  atlasFiles: Set<string>,
): string | null {
  const dir = path.dirname(jsonPath);
  const stem = path.basename(jsonPath, ".json");
  const ownAtlas = path.join(dir, `${stem}.atlas`);
  if (atlasFiles.has(ownAtlas)) {
    return toAssetPath(ASSETS_DIR, ownAtlas);
  }

  const atlasesInDir = [...atlasFiles].filter(
    (atlasPath) => path.dirname(atlasPath) === dir,
  );
  if (atlasesInDir.length === 1) {
    return toAssetPath(ASSETS_DIR, atlasesInDir[0]);
  }

  const folderAtlas = path.join(dir, `${path.basename(dir)}.atlas`);
  if (atlasFiles.has(folderAtlas)) {
    return toAssetPath(ASSETS_DIR, folderAtlas);
  }

  return null;
}

async function readAnimationNames(jsonPath: string): Promise<string[] | null> {
  const raw = await fs.readFile(jsonPath, "utf8");
  let document: SpineJsonDocument;
  try {
    document = JSON.parse(raw) as SpineJsonDocument;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`Skip ${toAssetPath(ASSETS_DIR, jsonPath)}: invalid JSON (${message})`);
    return null;
  }

  if (!document.skeleton || !document.animations) {
    console.warn(`Skip ${toAssetPath(ASSETS_DIR, jsonPath)}: not a Spine skeleton JSON`);
    return null;
  }

  return Object.keys(document.animations);
}

function buildAnimationGroups(
  skeletons: SpineSkeletonConfig[],
): SpineAnimationGroup[] {
  return Array.from({ length: ANIMATION_GROUP_COUNT }, (_, animationIndex) => ({
    id: animationIndex + 1,
    animationIndex,
    entries: skeletons.flatMap((skeleton) => {
      const animationName = skeleton.animations[animationIndex];
      if (!animationName) {
        return [];
      }
      return [{ skeletonId: skeleton.id, animationName }];
    }),
  }));
}

async function collectSkeletons(): Promise<SpineSkeletonConfig[]> {
  const files = await listFilesRecursive(ASSETS_DIR);
  const jsonFiles = [...collectByExtension(files, ".json")].sort();
  const skelFiles = collectByExtension(files, ".skel");
  const atlasFiles = collectByExtension(files, ".atlas");
  const skeletons: SpineSkeletonConfig[] = [];

  for (const jsonPath of jsonFiles) {
    const skelPath = jsonPath.slice(0, -".json".length) + ".skel";
    if (!skelFiles.has(skelPath)) {
      console.warn(`Skip ${toAssetPath(ASSETS_DIR, jsonPath)}: missing paired .skel`);
      continue;
    }

    const atlasPath = resolveAtlasPath(jsonPath, atlasFiles);
    if (!atlasPath) {
      console.warn(`Skip ${toAssetPath(ASSETS_DIR, jsonPath)}: atlas not found`);
      continue;
    }

    const animations = await readAnimationNames(jsonPath);
    if (!animations || animations.length === 0) {
      console.warn(`Skip ${toAssetPath(ASSETS_DIR, jsonPath)}: no animations`);
      continue;
    }

    skeletons.push({
      id: toAssetPath(ASSETS_DIR, jsonPath).replace(/\.json$/i, ""),
      jsonPath: toAssetPath(ASSETS_DIR, jsonPath),
      skelPath: toAssetPath(ASSETS_DIR, skelPath),
      atlasPath,
      animations,
    });
  }

  return skeletons;
}

function renderConfigModule(config: SpineAssetsConfig): string {
  return `/**
 * Auto-generated by \`npm run generate:spine-config\`.
 * Do not edit by hand — add Spine files to public/assets/ and regenerate.
 */
import type { SpineAssetsConfig } from "../types";

export const spineAssetsConfig: SpineAssetsConfig = ${JSON.stringify(
    config,
    null,
    2,
  )};
`;
}

function printSummary(config: SpineAssetsConfig): void {
  console.log(`Skeletons: ${config.skeletons.length}`);
  for (const skeleton of config.skeletons) {
    console.log(
      `  ${skeleton.id}  atlas=${skeleton.atlasPath}  animations=${skeleton.animations.join(", ")}`,
    );
  }

  console.log("\nAnimation groups:");
  for (const group of config.animationGroups) {
    console.log(
      `  Group ${group.id} (index ${group.animationIndex}): ${group.entries.length} skeletons`,
    );
    for (const entry of group.entries) {
      console.log(`    ${entry.skeletonId} -> ${entry.animationName}`);
    }
  }
}

async function main(): Promise<void> {
  const skeletons = await collectSkeletons();
  if (skeletons.length === 0) {
    throw new Error(`No Spine json+skel pairs found in ${ASSETS_DIR}`);
  }

  const config: SpineAssetsConfig = {
    generatedAt: new Date().toISOString(),
    assetsRoot: "/assets/",
    skeletons,
    animationGroups: buildAnimationGroups(skeletons),
  };

  await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  await fs.writeFile(OUTPUT_PATH, renderConfigModule(config), "utf8");

  console.log(`Wrote ${path.relative(ROOT_DIR, OUTPUT_PATH)}`);
  printSummary(config);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
